version: 2
updates:
  # Mantiene actualizadas las acciones de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Mantiene actualizadas las dependencias de Java / Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
